server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #这里连的是docker的MySQL容器,不是本地的
    url: jdbc:mysql://192.168.247.128:3306/tensquare_base?serverTimezone=UTC&characterEncoding=utf-8
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true