server: 
  port: 9002
spring: 
  application:  
    name: com.tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.247.128:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
